function [penm] = bmi_define(bmidata)
% define penm structure for bilinear SPD based on 'bmidata' structure
% Elements of the structure
%   name ... name of the problem (filename of SDPA file if the reader is used)
%   Nx ..... number of primal variables
%   Na ..... number of linear matrix inequalities (or diagonal blocks of the
%            matrix constraint)
%   Ng ..... number of linear inequalitites
%   B ...... matrix defining the linear inequality constraints Bx<=d
%            dimension Ng x Nx
%   d ...... rhs for linear constraints
%   c ...... dim (Nx,1), coefficients of the linear objective function
%   NaDims . vector of sizes of matrix constraints (diagonal blocks)
%   A ...... cell array (matrix) of A{k,l} for k=1,...,Na matrix constraint
%            for l=1 ~ absolute term, l=2..Nx+1 coeficient matrices
%            (some of them might be empty)
%   Adep ... rather create here vvv !!!

  % any checks on the data necessary???

  penm = [];

  if (isfield(bmidata,'name'))
    penm.probname=bmidata.name;
  end
  penm.comment = 'Structure PENM generated by sdp_define()';

  % keep the whole structure
  penm.userdata=bmidata;

  penm.Nx=bmidata.Nx;

  penm.NgLIN=bmidata.Ng;  %length(sdpdata.d);
  %penm.lbg = bmidata.d;
  penm.ubg = bmidata.d;

  penm.NANLN=bmidata.Na;
  % let's make it negative semidefinite
  penm.ubA=zeros(bmidata.Na,1);

  penm.objfun = @bmi_objfun;
  penm.objgrad = @bmi_objgrad;
  penm.objhess = @bmi_objhess;

  penm.confun = @bmi_confun;
  penm.congrad = @bmi_congrad;
  %penm.conhess = @sdp_conhess;  not needed because all linear

  penm.mconfun = @bmi_mconfun;
  penm.mcongrad = @bmi_mcongrad;
  penm.mconhess = @bmi_mconhess;
  % hessian not needed as linear


